config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homepage#index'
  
  namespace :account do
    resources :events
    resources :plans, only: [:index] do
      member do
        patch :switch
      end
    end
    resources :credit_cards, only: [:new, :create]

    scope :settings, controller: :settings do
      get :edit
      patch :update
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ReminderApp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'Reminder App', root_path, class: 'navbar-brand'
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              %a{:href => "#"}
                Link
                %span.sr-only (current)
          %ul.nav.navbar-nav.navbar-right
            - if current_user
              %li= link_to current_user.email, account_edit_path
              %li= link_to 'Log Out', destroy_user_session_path, method: :delete
    .col-sm-12
      - if notice
        .alert.alert-success= notice
      - if alert
        .alert.alert-danger= alert
      = yield